cache: bundler
language: ruby
rvm:
  - 2.6
  - 2.4
matrix:
  include:
    - rvm: 2.6
      env: JEKYLL_VERSION=3.8.6
env:
  matrix:
    - JEKYLL_VERSION=4.0.0.pre.alpha1
branches:
  only:
    - master
before_install:
- gem update --system
script: script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
